### PR TITLE
 fix setup.py and handle special case with zero gpus.

### PR DESCRIPTION
**Pull request by se4u**
Thanks for the effort to make onmt pth4 compatible.

It may be good to test the successful completion of the MT tutorial which is run nightly, or weekly, but not on every commit.

### CODE REVIEW

**Comment by se4u** [comment]
This comment is unrelated to the PR but rather related to the multigpu training script. I noticed that the performance of the multigpu training is quite a bit lower than the single gpu training after the same number of epochs. I used the standard data that is bundled with the OpenNMT package. Is this expected ?


[pth4.ubiquous.multigpu.log](https://github.com/Ubiqus/OpenNMT-py/files/2060691/pth4.ubiquous.multigpu.log)
[pth4.ubiquous.gpu.log](https://github.com/Ubiqus/OpenNMT-py/files/2060692/pth4.ubiquous.gpu.log)

**Comment by vince62s** [comment]
yes it is expected. the batch size is 4 times bigger.
in theory, you could expect 1 GPU batch size 4096 to be comparable with 4GPU batch size 1024
(in token mode) you can do the same in sentence mode. (ie 16 or 4x16)

**Comment by se4u** [comment]
ah I forgot about the batch size.  thanks for clearing this up.

**Comment by vince62s** [comment]
ok thanks for the PR, for some reason I edited the changes directly when people opened issues.
but thanks again, sorry.

**Pull request closed without merging**
